from flask import render_template
from app import app, cache

import os.path
import json
import logging

class ModelFormatError(Exception):
    pass

class RequestError(Exception):
    pass


# TODO: This function should be generalized
def get_accesslevels():
    if not hasattr(get_accesslevels, 'lastmtime'):
        get_accesslevels.lastmtime = 0

    newmtime = os.path.getmtime(app.config['FRONTEND_ACCESSLEVEL_FILE'])

    # Caching is disabled or the access levels file has changed, reload it
    if newmtime > get_accesslevels.lastmtime or not app.config['CACHE_ACCESSLEVELS']:
        get_accesslevels.lastmtime = newmtime
        accesslevels = json.load(file(app.config['FRONTEND_ACCESSLEVEL_FILE']))
        if app.config['CACHE_ACCESSLEVELS']:
            cache.set('accesslevels', accesslevels)

    if app.config['CACHE_ACCESSLEVELS']:
        return cache.get('accesslevels')
    else:
        return accesslevels

def get_model():
    if not hasattr(get_model, 'lastmtime'):
        get_model.lastmtime = 0

    newmtime = os.path.getmtime(app.config['FRONTEND_MODEL_FILE'])

    # Caching is disabled or the access levels file has changed, reload it
    if newmtime > get_model.lastmtime or not app.config['CACHE_MODEL']:
        get_model.lastmtime = newmtime
        model = json.load(file(app.config['FRONTEND_MODEL_FILE']))
        if app.config['CACHE_MODEL']:
            cache.set('model', model)

    if app.config['CACHE_MODEL']:
        return cache.get('model')
    else:
        return model


@app.route('/')
def index():
    accesslevels = get_accesslevels()
    return render_template("index.html", accesslevels=accesslevels)

@app.route('/form/<level>')
def form(level):
    accesslevels = get_accesslevels()
    model        = get_model()

    # NOTE: The model JSON may need to be cached for performance reasons
    #       The form HTML as generated by the template should be cached server-side as well

    if accesslevels is None or model is None:
        raise ModelFormatError('Could not load model description and access levels')

    for i, accesslevel in enumerate(accesslevels):
        if accesslevel['name'] == level:
            accesslevel_index = i
            break
    else:
        raise RequestError('Unknown access level specified')

    return render_template(
        'form.html',
        title='HADDOCK Form',
        accesslevels=accesslevels,
        accesslevel_index=accesslevel_index,
        model=model,
        user_accesslevel_index=2 # TODO: Get this information through auth
    )

